---
title: "Biosketch"
author: "Neha Solanki"
date: "2022-12-11"
categories: [Asthma]
---

\*\*A. Personal Statement\*\*

I am a pulmonologist and critical care intensivist with expertise in the management of severe and refractory asthma. During my clinical activities, I recognized that asthma presents differently based on the patient and requires a personalized treatment plan. These inherent differences relate to the underlying pathophysiologic mechanisms including inflammatory cytokines and airway remodeling. My understanding of this has led to my participation in the CHEST committee for Severe Asthma Biologics Guidelines. However, I soon realized that a significant driver of severe disease relates to the exposome, i.e. air pollution. Funded by an internal grant from the Center for Population Health Research in 2019, I demonstrated the relationship between nitrogen dioxide and asthma severity and presented my findings as a finalist for the Sixteenth National Jewish Young Investigators' Forum in 2020 and have a manuscript close to being published in Pediatric Pulmonology. Concurrently, I wrote an article on air pollution and asthma for the \[ATS Springer Edition: Lung Health and Exposome\]{.underline} entitled "Air Matters: The Effect of Ozone and Traffic Related Air Pollution on the Airways." My interest in these projects led me to become an active member of the American Thoracic Society (ATS) Environmental and Occupational Population Health (EOPH) early career professional's working group where I served as the web apprentice from 2021-2022. In 2022, I organized and chaired an ATS panel entitled "The Full Picture: Asthma as a Case Study in the Complexities of Exposure." During this panel, I leveraged the knowledge of international experts on the exposome and developed multiple collaborations. Inspired by these colleagues, I sought to improve asthma on the local level by working with the Legal Aid Society of Cleveland. In this innovative community partnership, we seek to implement a mechanism to improve indoor housing quality in children with severe asthma to improve lung health. Our ongoing work has been recently funded by a competitive internal grant known as the Caregiver Catalyst starting in 2022.

Simultaneously, I have sought to determine the relationship between asthma severity and cytokine release due to platelet activation. Triggers such as pollution in the exposome effect cytokine release in asthma. This interest in translational research began during my fellowship when I worked in a laboratory to investigate the relationship between cytokines and ventilatory pattern variations in septic mice. Cytokines play a large role in asthma and pro-inflammatory cytokines can activate platelets which may play a role in the onset of asthma. I presented an abstract at the American Thoracic Society in 2020 demonstrating that asthma severity was associated with higher platelets in the National Health and Nutrition Examination Survey (NHANES) and currently have a manuscript nearing completion expanding on these findings in multiple datasets including SARPIII and the UK biobank.

My long-term goal is to become an independently-funded leader in the field of the exposome and asthma.
